version: '3.4'

services:
  cronschedulewebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44369
      - ConnectionStrings:DefaultConnection=Server=cronschedulewebapp.sql;Database=CronSchedulerApp;User Id=sa;Password=Pass@word
    ports:
      - "57989:80"
      - "44369:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  cronschedulewebapp.sql:
    ports:
     - "5467:1433"
    environment:
     - SA_PASSWORD=Pass@word
     - ACCEPT_EULA=Y
