version: '3.4'

services:
  cronschedulewebapp:
    image: ${DOCKER_REGISTRY}cronschedulewebapp
    build:
      context: .
      dockerfile: src/WebTestApp/Dockerfile

  cronschedulewebapp.sql:
    image: microsoft/mssql-server-linux:2017-latest
